const initialState = {
  '1984': `Nineteen Eighty-Four, often published as 1984, is a dystopian novel published in 1949 by English author George Orwell.The novel is set in Airstrip One (formerly known as Great Britain), a province of the superstate Oceania in a world of perpetual war, omnipresent government surveillance, and public manipulation. The superstate and its residents are dictated to by a political regime euphemistically named English Socialism, shortened to "Ingsoc" in Newspeak, the government's invented language. The superstate is under the control of the privileged elite of the Inner Party, a party and government that persecutes individualism and independent thinking as "thoughtcrime", which is enforced by the "Thought Police"`,

  'Animal Farm': `As ferociously fresh as it was more than a half century ago, this remarkable allegory of a downtrodden society of overworked, mistreated animals, and their quest to create a paradise of progress, justice, and equality is one of the most scathing satires ever published. As we witness the rise and bloody fall of the revolutionary animals, we begin to recognize the seeds of totalitarianism in the most idealistic organization; and in our most charismatic leaders, the souls of our cruelest oppressors.`,

  'Wake in Fright': `The Film Ink series presents the novels that inspired the work of some of the most celebrated directors of our time. While each novel is first and foremost a classic in its own right, these books offer the dedicated cinephile a richer understanding of the most illustrious films of American and European cinema. Wake In Fright was first published in 1961 and the film version, The Outback, starring Donald Pleasance was released in 1971. Both the book and the film have achieved a cult status as the Australian answer to US and UK novels and films of 1960s youthful alienation. It is the gruelling story of a young Australian schoolteacher on his way back from the outback to Sydney and civilization when things start to go wrong. He finds himself stuck overnight in Bundanyabba, a rough outback mining town. An ill-advised and drink-fuelled visit to a gambling den leaves Grant broke and he realizes he has no way of escaping. He descends into a cycle of hangovers, fumbling sexual encounters, and increasing self-loathing as he becomes more and more immersed in the grotesque and surreal nightmare that his life has become. `,

  'Capricornia. A Novel of North Australia': `Capricornia is the debut novel by Xavier Herbert.\n\nLike his later work considered by many a masterpiece, the Miles Franklin Award-winning Poor Fellow My Country, it provides a fictional account of life in 'Capricornia', a place clearly modelled specifically on Australia's Northern Territory, and to a lesser degree on tropical Australia in general, (i.e. anywhere north of the Tropic of Capricorn) in the early twentieth century. It was written in London between 1930 and 1932.`,

  'Voss': `Set in nineteenth-century Australia, Voss is the story of the secret passion between an explorer and a naïve young woman. Although they have met only a few times, Voss and Laura are joined by overwhelming, obsessive feelings for each other. Voss sets out to cross the continent, and as hardships, mutiny and betrayal whittle away his power to endure and to lead, his attachment to Laura gradually increases. Laura, waiting in Sydney, moves through the months of separation as if they were a dream and Voss the only reality.`,

  'Down and Out in Paris and London': `This unusual fictional account - in good part autobiographical - narrates without self-pity and often with humor the adventures of a penniless British writer among the down-and-out of two great cities. The Parisian episode is fascinating for its expose of the kitchens of posh French restaurants, where the narrator works at the bottom of the culinary echelon as dishwasher, or plongeur. In London, while waiting for a job, he experiences the world of tramps, street people, and free lodging houses. In the tales of both cities we learn some sobering Orwellian truths about poverty and society.`,

  'Burmese Days': `Burmese Days is a novel by British writer George Orwell. It was first published in the United Kingdom in 1934. It is a tale from the waning days of British colonialism, when Burma was ruled from Delhi as a part of British India – "a portrait of the dark side of the British Raj.
  At its centre is John Flory, "the lone and lacking individual trapped within a bigger system that is undermining the better side of human nature."Orwell's first novel, it describes "corruption and imperial bigotry" in a society where, "after all, natives were natives—interesting, no doubt, but finally...an inferior people"`,

  'A Collection of Essays': `George Orwell's collected nonfiction, written in the clear-eyed and uncompromising style that earned him a critical following. One of the most thought-provoking and vivid essayists of the twentieth century, George Orwell fought the injustices of his time with singular vigor through pen and paper. In this selection of essays, he ranges from reflections on his boyhood schooling and the profession of writing to his views on the Spanish Civil War and British imperialism. The pieces collected here include the relatively unfamiliar and the more celebrated, making it an ideal compilation for both new and dedicated readers of Orwell's work.`,

  'Holy Bible': `This up-to-date version of the universally accepted text from the King James Bible will make a handsome addition to any home. The revised translation is easily accessible for the modern reader, and is based on the original King James Version, published in 1611. In the course of time, the King James Version came to be regarded as "the Authorized Version.” It has been termed the "noblest monument of English prose,” and it has come to be of central importance to Western society as no other book. Thunder Bay’s Holy Bible is beautifully appointed and illustrated with reproductions of original fifteenth-century masterpieces, highlighting Renaissance masterpieces from the period of 1430 to 1510. Almost every page of the Holy Bible has illuminated accents, with evocative drawings throughout from the Vatican Library, and an overall design inspired by the peerless Urbino Bible of 1478. The Holy Bible is complete with beautiful pages on which to lovingly record marriages, births, baptisms, confirmations, deaths, and family trees.`,

  'How To Draw Comics The Marvel Way': `Stan Lee, the Mighty Man from Marvel, and John Buscema, active and adventuresome artist behind the Silver Surfer, Conan the Barbarian, the Mighty Thor and Spider-Man, have collaborated on this comics compendium: an encyclopedia of information for creating your own superhero comic strips. Using artwork from Marvel comics as primary examples, Buscema graphically illustrates the hitherto mysterious methods of comic art. Stan Lee's pithy prose gives able assistance and advice to the apprentice artist. Bursting with Buscema's magnificent illustrations and Lee's laudable word-magic, How to Draw Comics the Marvel Way belongs in the library of every kid who has ever wanted to illustrate his or her own comic strip.`,

}

export default (state = initialState, action) => state;